# Generated by Django 6.0.3 on 2026-03-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название альбома')),
                ('artist', models.CharField(max_length=200, verbose_name='Исполнитель')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
                ('cover_url', models.URLField(blank=True, verbose_name='URL обложки')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Год выпуска')),
            ],
            options={
                'verbose_name': 'Альбомы',
            },
        ),
    ]
