# Generated by Django 6.0.3 on 2026-04-01 17:33

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_album_options_album_author_album_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=catalog.models.upload_cover_path, verbose_name='Обложка (файл)'),
        ),
    ]
